workflows:
  react-native:
    name: simple-ios-todo
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "value here"
        XCODE_SCHEME: "value here"
        # iOS automatic code signing
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
      xcode: latest
      node: latest
      npm: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
            - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
              script: keychain initialize
            - name: Fetch signing files
              script: |
                app-store-connect fetch-signing-files "io.codemagic.app" \  # Fetch signing files for specified bundle ID (use "$(xcode-project detect-bundle-id)" if not specified)
                  --type IOS_APP_DEVELOPMENT \  # Specify provisioning profile type*
                  --create  # Allow creating resources if existing are not found.      
            - name: Set up signing certificate
              script: keychain add-certificates
            - name: Set up code signing settings on Xcode project
              script: xcode-project use-profiles
            - |
                # build iOS
                cd ios
                pod install
                xcodebuild build -workspace "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - name@example.com
      scripts:
        - echo 'Post-publish script'
